# Generated by Django 2.1.3 on 2018-11-16 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('postImage', models.FileField(upload_to='')),
                ('category', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PUB', 'Published'), ('DRF', 'Draft')], max_length=3)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
