# Generated by Django 2.1.3 on 2018-11-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postImage',
            new_name='image',
        ),
    ]
