# Generated by Django 2.1.3 on 2018-11-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181119_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
