# Generated by Django 2.1.3 on 2018-11-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20181116_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
